library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
rstan_options(javascript = FALSE)

tsmr_delta_2014thru2018 <- readRDS("tsmr_stan_data_list.rds")

TSMSMRtaglife_2014thru2018 <- stan("TSMSMR_WinterRun_2014-2018_TagLifeCorrection.stan",
                                                data = tsmr_delta_2014thru2018,
                                                chains = 4,
                                                iter = 2000,
                                                pars = c("alpha_s1_t0_14", "alpha_s1_t0_15",
                                                         "alpha_s1_t0_16", "alpha_s1_t0_17",
                                                         "alpha_s1_t0_18",
                                                         "beta_phi_s1_t0_14", "beta_phi_s1_t0_15",
                                                         "beta_phi_s1_t0_16",  "beta_phi_s1_t0_17",
                                                         "beta_phi_s1_t0_18",
                                                         "beta_phi_s1_t1", 
                                                         "beta_phi_s1_t3",
                                                         "beta_phi_s1_t4", "beta_phi_s1_t5",
                                                         "beta_phi_s1_t6", "beta_phi_s1_t7",
                                                         "beta_phi_s1_t8", "beta_phi_s1_t9",
                                                         "beta_phi_s2_t3", "beta_phi_s2_t8",
                                                         "beta_phi_s3_t8", "beta_phi_s4_t8",
                                                         "beta_phi_s5_t8", "beta_phi_s5_t9",
                                                         "chipps2benecia",
                                                         
                                                         "beta_psi_1to2_t2",
                                                         "beta_psi_1to3_t6",
                                                         "beta_psi_1to4_t6", "beta_psi_1to5_t7",
                                                         
                                                         "beta_p_s1_t1_14",  "beta_p_s1_t4_14",
                                                         "beta_p_s1_t5_14", "beta_p_s1_t6_14",
                                                         "beta_p_s1_t7_14", "beta_p_s1_t8_14",
                                                         "beta_p_s1_t9_14", "beta_p_s3_t7_14",
                                                         "beta_p_s5_t8_14", "beta_p_s5_t9_14",
                                                         
                                                         "beta_p_s1_t1_15",  "beta_p_s1_t4_15",
                                                         "beta_p_s1_t5_15", "beta_p_s1_t6_15",
                                                         "beta_p_s1_t7_15", "beta_p_s1_t8_15",
                                                         "beta_p_s1_t9_15", "beta_p_s3_t7_15",
                                                         "beta_p_s5_t8_15", "beta_p_s5_t9_15",
                                                         
                                                         "beta_p_s1_t1_16", "beta_p_s1_t4_16",
                                                         "beta_p_s1_t5_16", "beta_p_s1_t6_16",
                                                         "beta_p_s1_t7_16",
                                                         "beta_p_s1_t9_16", "beta_p_s1_t10_16",
                                                         "beta_p_s2_t4_16", "beta_p_s3_t7_16",
                                                         "beta_p_s5_t9_16",
                                                         
                                                         "beta_p_s1_t1_17", "beta_p_s1_t2_17",
                                                         "beta_p_s1_t3_17", "beta_p_s1_t4_17",
                                                         "beta_p_s1_t5_17", "beta_p_s1_t6_17",
                                                         "beta_p_s1_t7_17", "beta_p_s1_t8_17",
                                                         "beta_p_s1_t9_17", "beta_p_s1_t10_17",
                                                         "beta_p_s2_t4_17", "beta_p_s3_t7_17",
                                                         "beta_p_s5_t9_17",
                                                         
                                                         "beta_p_s1_t1_18", "beta_p_s1_t2_18",
                                                         "beta_p_s1_t3_18", "beta_p_s1_t4_18",
                                                         "beta_p_s1_t5_18", "beta_p_s1_t6_18",
                                                         "beta_p_s1_t7_18", "beta_p_s1_t8_18",
                                                         "beta_p_s1_t9_18", "beta_p_s1_t10_18",
                                                         "beta_p_s2_t4_17", "beta_p_s3_t7_18",
                                                         "beta_p_s5_t8_18", "beta_p_s5_t9_18",
                                                         
                                                         "beta_p_s3_t7_14",  "beta_p_s3_t7_15",
                                                         "beta_p_s3_t7_16",  "beta_p_s3_t7_17",
                                                         "beta_p_s3_t7_18",
                                                         
                                                         "mu_v_s1_t0_14", "sigma_v_s1_t0_14", 
                                                         "mu_v_s1_t0_15", "sigma_v_s1_t0_15", 
                                                         "mu_v_s1_t0_16", "sigma_v_s1_t0_16",
                                                         "mu_v_s1_t0_17", "sigma_v_s1_t0_17",
                                                         "mu_v_s1_t0_18", "sigma_v_s1_t0_18", 
                                                         
                                                         "beta_mu_s1_t1", "sigma_tt_s1_t1",
                                                         "beta_mu_s1_t2b", "sigma_tt_s1_t2b",
                                                         
                                                         "beta_mu_s1_t2", "sigma_tt_s1_t2",
                                                         "beta_mu_s1_t3", "sigma_tt_s1_t3",
                                                         "beta_mu_s1_t4", "sigma_tt_s1_t4",
                                                         "beta_mu_s1_t5", "sigma_tt_s1_t5",
                                                         "beta_mu_s1_t6", "sigma_tt_s1_t6",
                                                         "beta_mu_s1_t7", "sigma_tt_s1_t7",
                                                         "beta_mu_s1_t8", "sigma_tt_s1_t8",
                                                         "beta_mu_s1_t9", "sigma_tt_s1_t9",

                                                         "beta_mu_s1_t10", "sigma_tt_s1_t10",
                                                         "beta_mu_s2_t3", "sigma_tt_s2_t3",
                                                         "beta_mu_s2_t8", "sigma_tt_s2_t8",
                                                         "beta_mu_s3_t8", "sigma_tt_s3_t8",
                                                         "beta_mu_s4_t8", "sigma_tt_s4_t8",
                                                         "beta_mu_s5_t8", "sigma_tt_s5_t8",
                                                         "beta_mu_s5_t9", "sigma_tt_s5_t9",

                                                         "overall_survival_14", "prop_sacra_14",
                                                         "prop_sutter_14", "prop_steam_14",
                                                         "prop_georg_14", "chipps_arrival_dist_14",
                                                         "overall_survival_from_KL_14",
                                                         "route_survival_from_KL_14",
                                                         "route_probability_from_KL_14",
                                                         
                                                         "overall_survival_15", "prop_sacra_15",
                                                         "prop_sutter_15", "prop_steam_15",
                                                         "prop_georg_15", "chipps_arrival_dist_15",
                                                         "overall_survival_from_KL_15",
                                                         "route_survival_from_KL_15",
                                                         "route_probability_from_KL_15",
                                                         
                                                         "overall_survival_16", "prop_sacra_16",
                                                         "prop_yolo_16", "prop_sutter_16", "prop_steam_16",
                                                         "prop_georg_16", "chipps_arrival_dist_16",
                                                         "overall_survival_from_KL_16",
                                                         "route_survival_from_KL_16",
                                                         "route_probability_from_KL_16",
                                                         
                                                         "overall_survival_17", "prop_sacra_17",
                                                         "prop_yolo_17", "prop_sutter_17", "prop_steam_17",
                                                         "prop_georg_17", "chipps_arrival_dist_17",
                                                         "overall_survival_from_KL_17",
                                                         "route_survival_from_KL_17",
                                                         "route_probability_from_KL_17",
                                                         
                                                         "overall_survival_18", "prop_sacra_18",
                                                         "prop_yolo_18",
                                                         "prop_sutter_18", "prop_steam_18",
                                                         "prop_georg_18", "chipps_arrival_dist_18",
                                                         "overall_survival_from_KL_18",
                                                         "route_survival_from_KL_18",
                                                         "route_probability_from_KL_18"
                                                ),
                                                init = function(){
                                                  
                                                  list(beta_phi_s1_t0_14 = runif(1, -0.2, 0.2),
                                                       beta_phi_s1_t0_15 = runif(1, -0.2, 0.2),
                                                       beta_phi_s1_t0_16 = runif(1, 0.2, 0.4),
                                                       beta_phi_s1_t0_17 = runif(1, -0.2, 0.2),
                                                       beta_phi_s1_t0_18 = runif(2, -0.2, 0.2),
                                                       
                                                       beta_phi_s1_t1 = c(runif(1, 3, 4), runif(1, 0, 2), runif(1, -1, 1)),

                                                       beta_phi_s1_t3 = c(runif(1, 3, 4), runif(1, -1, 1), runif(1, -1, 1)),
                                                       beta_phi_s1_t4 = c(runif(1, 3.5, 4.5), runif(1, 0, 1.5), runif(1, -1, 1)),
                                                       beta_phi_s1_t5 = c(runif(1, 4.5, 5.5), runif(1, -1, 1), runif(1, -1, 1)),
                                                       beta_phi_s1_t6 = c(runif(1, 3, 4.5), runif(1, 1.25, 3.25), runif(1, -1, 1)),
                                                       beta_phi_s1_t7 = c(runif(1, 2.5, 3.5), runif(1, 1.5, 3), runif(1, -1, 1)),
                                                       beta_phi_s1_t8 = c(runif(1, 2, 3.5), runif(1, 0.5, 2), runif(1, -1, 1)),
                                                       beta_phi_s1_t9 = c(runif(1, 1.5, 2), runif(1, 0, 0.5), runif(1, -1, 1)),
                                                       beta_phi_s2_t3 = c(runif(1, 1.5, 3.5), runif(1, 0, 2), runif(1, -1, 1)),
                                                       beta_phi_s2_t8 = c(runif(1, 0.5, 2), runif(1, 0.0, 2), runif(1, -1, 1)),
                                                       beta_phi_s3_t8 = c(runif(1, 0.75, 1.75), runif(1, 0.5, 1.5), runif(1, -1, 1)),
                                                       beta_phi_s4_t8 = c(runif(1, 1, 2.5), runif(1, 1, 2), runif(1, -1, 1)),
                                                       beta_phi_s5_t8 = c(runif(1, 2, 3.5), runif(1, -1, 1), runif(1, -1, 1)),
                                                       beta_phi_s5_t9 = c(runif(1, -2.5, -1), runif(1, -0.5, 1.5), runif(2, -1, 1)),
                                                       chipps2benecia = runif(1, 0.6, 0.65),
                                                       beta_psi_1to2_t2 = c(runif(1, -2.5, -1), runif(1, 0, 1.5)),
                                                       beta_psi_1to3_t6 = c(runif(1, -2, -1.6), runif(1, -0.4, 0.4)),
                                                       beta_psi_1to4_t6 = c(runif(1, -2.25, -1.75), runif(1, -0.5, 0)),
                                                       beta_psi_1to5_t7 = c(runif(1, -1.75, -1.25), runif(1, -0.5, 0)),
                                                       
                                                       beta_p_s1_t1_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s1_t4_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s1_t5_15   = c(runif(1, -0.5, 0.5),  runif(1, -2, -1)),
                                                       beta_p_s1_t6_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s1_t7_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s1_t8_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s1_t9_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s3_t7_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s5_t8_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       beta_p_s5_t9_15   = c(runif(1, 0, 1),  runif(1, -2, -1)),
                                                       
                                                       beta_p_s1_t1_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t4_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t5_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t6_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t7_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t9_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t10_16  = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s2_t4_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s3_t7_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s5_t9_16   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       
                                                       beta_p_s1_t1_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t2_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t3_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t4_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t5_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t6_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t7_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t8_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t9_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s1_t10_17  = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s2_t4_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s3_t7_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s5_t8_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       beta_p_s5_t9_17   = c(runif(1, 0, 1),  runif(1, -2, -0.5)),
                                                       
                                                       mu_v_s1_t0_14 = runif(1, 2.0, 2.5),
                                                       mu_v_s1_t0_15 = runif(1, 2.0, 2.5),
                                                       mu_v_s1_t0_16 = runif(1, 2.0, 2.5),
                                                       mu_v_s1_t0_17 = runif(1, 2.0, 2.5),
                                                       mu_v_s1_t0_18 = runif(2, 2.0, 2.5),
                                                       
                                                       sigma_v_s1_t0_14 = runif(1, 1, 2),
                                                       sigma_v_s1_t0_15 = runif(1, 1, 2),
                                                       sigma_v_s1_t0_16 = runif(1, 1, 2),
                                                       sigma_v_s1_t0_17 = runif(1, 1, 2),
                                                       sigma_v_s1_t0_18 = runif(1, 1, 2),
                                                       
                                                       beta_mu_s1_t1   = c(runif(1, -2, -1), runif(1, -0.25, 025)),
                                                       sigma_tt_s1_t1  = runif(1, 0.75, 1.25),
                                                       beta_mu_s1_t2b   = c(runif(1, -1, 0), runif(1, -4, -3)),
                                                       sigma_tt_s1_t2b  = runif(1, 1.4, 1.8),  
                                                       beta_mu_s1_t2   = c(runif(1, -1.5, -0.5), runif(1, -0.25, 0.25)),
                                                       sigma_tt_s1_t2  = runif(1, 0.75, 1),
                                                       beta_mu_s1_t3   = c(runif(1, -1, -0.4), runif(1, 0.0, 0.5)),
                                                       sigma_tt_s1_t3  = runif(1, 0.6, 1),
                                                       beta_mu_s1_t4   = c(runif(1, -0.1, 0.1), runif(1, -0.75, -0.25)),
                                                       sigma_tt_s1_t4  = runif(1, 0.5, 0.6),
                                                       beta_mu_s1_t5   = c(runif(1, -0.05, 0.0), runif(1, -0.125, -0.075)),
                                                       sigma_tt_s1_t5  = runif(1, 0.375, 0.425),
                                                       beta_mu_s1_t6   = c(runif(1, -2.5, -1), runif(1, -2.5, -1.25)),
                                                       sigma_tt_s1_t6  = runif(1, 0.275, 0.4),
                                                       beta_mu_s1_t7   = c(runif(1, -0.3, 0.2), runif(1, -0.2, 0.0)),
                                                       sigma_tt_s1_t7  = runif(1, 0.2, 0.5),
                                                       beta_mu_s1_t8   = c(runif(1, 0.1, 0.15), runif(1, -0.25, -0.125)),
                                                       sigma_tt_s1_t8  = runif(1, 0.35, 0.425),
                                                       beta_mu_s1_t9   = c(runif(1, 0.7, 0.8), runif(1, -0.275, -0.125)),
                                                       sigma_tt_s1_t9  = runif(1, 0.48, 0.55),
                                                       beta_mu_s1_t10   = runif(1, 0.475, 0.525),
                                                       sigma_tt_s1_t10  = runif(1, 0.475, 0.525),
                                                       
                                                       beta_mu_s2_t3   = c(runif(1, 2.5, 5), runif(1, -1, 1)),
                                                       sigma_tt_s2_t3  = runif(1, 1, 2),
                                                       beta_mu_s2_t8   = c(runif(1, 0.5, 1.5), runif(1, -1, 0)),
                                                       sigma_tt_s2_t8  = runif(1, 0.5, 0.75),
                                                       
                                                       beta_mu_s3_t8   = c(runif(1, 0.5, 1.5), runif(1, -1, 0)),
                                                       sigma_tt_s3_t8  = runif(1, 0.5, 0.65),
                                                       beta_mu_s4_t8   = c(runif(1, 0.1, 0.3), runif(1, -0.3, 0)),
                                                       sigma_tt_s4_t8  = runif(1, 0.4, 0.6),
                                                       
                                                       beta_mu_s5_t8   = c(runif(1, -0.1, 0.0), runif(1, -0.2, 0)),
                                                       sigma_tt_s5_t8  = runif(1, 0.2, 0.4),
                                                       beta_mu_s5_t9   = c(runif(1, 1.6, 1.8), runif(1, -0.5, -0.2)),
                                                       sigma_tt_s5_t9  = runif(1, 0.25, 0.4)#,

                                                  )
                                                }#,
                                                #control = list(adapt_delta = 0.95, 
                                                #                max_treedepth = 12)
                                                
)